In [33]:
import torch

In [34]:
import numpy as np

### torch 基本处理单元

In [35]:
# 返回的数组大小5x4的矩阵
a = torch.Tensor(5,4)
a

tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000,    nan, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])

In [36]:
# 返回的数组大小是5x4的矩阵，初始化是0~1的均匀分布
torch.rand(5, 4)

tensor([[0.0183, 0.1020, 0.9229, 0.7919],
        [0.3963, 0.5906, 0.3186, 0.4597],
        [0.1792, 0.8656, 0.6486, 0.2832],
        [0.2041, 0.2687, 0.8877, 0.0685],
        [0.3728, 0.3687, 0.9240, 0.6478]])

In [37]:
# 得到矩阵大小
torchtensor = torch.rand(5, 4)
print(torchtensor)
print(torchtensor.size())

tensor([[0.7286, 0.6617, 0.4844, 0.6407],
        [0.4961, 0.0734, 0.6385, 0.3460],
        [0.6275, 0.4987, 0.2483, 0.0126],
        [0.3542, 0.9990, 0.2551, 0.3168],
        [0.7882, 0.1038, 0.2403, 0.3592]])
torch.Size([5, 4])


In [38]:
# numpy 类似的返回5x4大小的矩阵
np.ones((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
numpymatrix = np.random.random((3, 2))
print(numpymatrix)

[[0.93169264 0.3936658 ]
 [0.59703753 0.48359814]
 [0.87246651 0.76637981]]


In [58]:
# numpy 和 torch.Tensor 之间的转换
a = torch.rand(5, 4)
b = a.numpy()
print(a,'\n')
print(b,'\n')
print(a.size(),'\n')
print(b.shape,'\n')


tensor([[0.0669, 0.9060, 0.3608, 0.9418],
        [0.3516, 0.8702, 0.5445, 0.4022],
        [0.9874, 0.2100, 0.5974, 0.6802],
        [0.8322, 0.8618, 0.9479, 0.7109],
        [0.7188, 0.1994, 0.0152, 0.5384]]) 

[[0.06686485 0.90599525 0.36078322 0.94182914]
 [0.35164225 0.870247   0.54450774 0.4021746 ]
 [0.98739105 0.2100156  0.5974472  0.6801666 ]
 [0.8322172  0.8618167  0.94787705 0.7108633 ]
 [0.7188453  0.199435   0.015248   0.5383508 ]] 

torch.Size([5, 4]) 

(5, 4) 



In [56]:
a = np.array([[3, 4], [3, 6]])
b = torch.from_numpy(a)

print(a,'\n')
print(b,'\n')
print(a.shape,'\n')
print(b.size(),'\n')

[[3 4]
 [3 6]] 

tensor([[3, 4],
        [3, 6]], dtype=torch.int32) 

(2, 2) 

torch.Size([2, 2]) 



In [69]:
from numpy import *
a = array([[1, 3], [2, 4], [5, 6]])
print(a.shape)

(3, 2)


In [9]:
x_train = np.array([[3.3], [4.4], [5.5], [6.71], [6.93], [4.168],
                    [9.779], [6.182], [7.59], [2.167], [7.042],
                    [10.791], [5.313], [7.997], [3.1]], dtype=np.float32)
x_train = torch.from_numpy(x_train)
x_train

tensor([[ 3.3000],
        [ 4.4000],
        [ 5.5000],
        [ 6.7100],
        [ 6.9300],
        [ 4.1680],
        [ 9.7790],
        [ 6.1820],
        [ 7.5900],
        [ 2.1670],
        [ 7.0420],
        [10.7910],
        [ 5.3130],
        [ 7.9970],
        [ 3.1000]])

In [24]:
x = np.zeros((3, 5, 2), dtype=np.complex128)
#np.prod(x.shape)
np.size(x)
len(x)

3

In [10]:
type(x_train)

torch.Tensor

运算和numpy类似

In [18]:
x = torch.rand(5, 4)
y = torch.rand(5, 4)
c = 3
x

tensor([[0.0664, 0.5140, 0.3413, 0.6868],
        [0.4688, 0.5812, 0.4567, 0.5556],
        [0.8264, 0.8533, 0.8824, 0.9460],
        [0.0607, 0.6102, 0.6844, 0.9470],
        [0.7700, 0.8871, 0.6622, 0.2189]])

In [20]:
print(c * x)
print(y)

tensor([[0.1992, 1.5420, 1.0238, 2.0605],
        [1.4063, 1.7435, 1.3701, 1.6668],
        [2.4793, 2.5600, 2.6473, 2.8380],
        [0.1821, 1.8307, 2.0531, 2.8409],
        [2.3101, 2.6613, 1.9865, 0.6567]])
tensor([[0.9534, 0.1911, 0.6159, 0.3474],
        [0.9107, 0.4464, 0.5194, 0.7155],
        [0.2504, 0.1092, 0.0749, 0.4053],
        [0.1373, 0.6465, 0.2087, 0.2540],
        [0.3218, 0.9872, 0.5132, 0.4637]])


In [21]:
print(x + y)

tensor([[1.0198, 0.7051, 0.9572, 1.0342],
        [1.3794, 1.0276, 0.9761, 1.2711],
        [1.0769, 0.9625, 0.9573, 1.3513],
        [0.1980, 1.2567, 0.8931, 1.2009],
        [1.0918, 1.8743, 1.1754, 0.6826]])


In [23]:
print(x.add(y))
print(x)

tensor([[1.0198, 0.7051, 0.9572, 1.0342],
        [1.3794, 1.0276, 0.9761, 1.2711],
        [1.0769, 0.9625, 0.9573, 1.3513],
        [0.1980, 1.2567, 0.8931, 1.2009],
        [1.0918, 1.8743, 1.1754, 0.6826]])
tensor([[0.0664, 0.5140, 0.3413, 0.6868],
        [0.4688, 0.5812, 0.4567, 0.5556],
        [0.8264, 0.8533, 0.8824, 0.9460],
        [0.0607, 0.6102, 0.6844, 0.9470],
        [0.7700, 0.8871, 0.6622, 0.2189]])


In [24]:
# 可以直接进行操作改变原对象，x+y或者x.add()并不会改变x，但是x.add_()则会对x进行改变
x.add_(y)
print(x)

tensor([[1.0198, 0.7051, 0.9572, 1.0342],
        [1.3794, 1.0276, 0.9761, 1.2711],
        [1.0769, 0.9625, 0.9573, 1.3513],
        [0.1980, 1.2567, 0.8931, 1.2009],
        [1.0918, 1.8743, 1.1754, 0.6826]])


In [25]:
print(x)

tensor([[1.0198, 0.7051, 0.9572, 1.0342],
        [1.3794, 1.0276, 0.9761, 1.2711],
        [1.0769, 0.9625, 0.9573, 1.3513],
        [0.1980, 1.2567, 0.8931, 1.2009],
        [1.0918, 1.8743, 1.1754, 0.6826]])


将 torch.Tensor 放到 GPU 上

In [26]:
# 判断一下电脑是否支持GPU
torch.cuda.is_available()

True

In [28]:
a = torch.rand(5, 4)
#a = a.cuda()
print(a)

tensor([[0.4459, 0.4001, 0.0289, 0.7369],
        [0.5530, 0.2841, 0.6589, 0.4691],
        [0.3124, 0.4304, 0.2910, 0.7345],
        [0.9492, 0.3983, 0.0062, 0.8460],
        [0.7582, 0.4797, 0.6888, 0.6493]])


### torch 的自动求导功能
torch 和大部分框架一样有着自动求导功能，对象不再是 torch.Tensor，而是torch.autograd.Variable

本质上Variable和Tensor没有什么区别，不过Variable会放在一个计算图里面，可以进行前向传播和反向传播以及求导  

![1.png](http://upload-images.jianshu.io/upload_images/3623720-1c2694b72e0341ce.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

里面的creator表示通过什么操作得到的这个Variable，grad表示反向传播的梯度

In [29]:
a = a.cuda()
print(a)

tensor([[0.4459, 0.4001, 0.0289, 0.7369],
        [0.5530, 0.2841, 0.6589, 0.4691],
        [0.3124, 0.4304, 0.2910, 0.7345],
        [0.9492, 0.3983, 0.0062, 0.8460],
        [0.7582, 0.4797, 0.6888, 0.6493]], device='cuda:0')


In [71]:
from torch.autograd import Variable

In [72]:
# requires_grad 表示是否对其求梯度，默认是False
x = Variable(torch.Tensor([3]), requires_grad=True)
y = Variable(torch.Tensor([5]), requires_grad=True)
z = 2 * x + y**2 + 4

In [73]:
x

tensor([3.], requires_grad=True)

In [35]:
# 对 x 和 y 分别求导
z.backward()

In [36]:
# x 的导数和 y 的导数
print('dz/dx: {}'.format(x.grad.data))
print('dz/dy: {}'.format(y.grad.data))

dz/dx: tensor([2.])
dz/dy: tensor([10.])


### 神经网络部分

所依赖的主要是 torch.nn 和 torch.nn.functional

torch.nn 里面有着所有的神经网络的层的操作，其用来构建网络，只有执行一次网络的运算才执行一次

torch.nn.functional 表示的是直接对其做一次向前运算操作

In [37]:
from torch import nn
import torch.nn.functional as F

In [38]:
# 基本的网络构建类模板
class net_name(nn.Module):
    def __init__(self):
        super(net_name, self).__init__()
        # 可以添加各种网络层
        self.conv1 = nn.Conv2d(3, 10, 3)
        # 具体每种层的参数可以去查看文档
        
    def forward(self, x):
        # 定义向前传播
        out = self.conv1(x)
        return out