In [7]:
import torch
import torch.nn.functional as F


# replace following class code with an easy sequential network
class Net(torch.nn.Module):
    def __init__(self, n_feature, n_hidden, n_output):
        super(Net, self).__init__()
        self.hidden = torch.nn.Linear(n_feature, n_hidden)   # hidden layer
        self.predict = torch.nn.Linear(n_hidden, n_output)   # output layer

    def forward(self, x):
        x = F.relu(self.hidden(x))      # activation function for hidden layer
        x = self.predict(x)             # linear output
        return x
net1 = Net(1, 10, 1)

# easy and fast way to build your network
net2 = torch.nn.Sequential(
    torch.nn.Linear(1, 10),
    torch.nn.Sigmoid(),
    torch.nn.ReLU(),
    torch.nn.Linear(10, 1)
)


print(net1)     # net1 architecture
"""
Net (
  (hidden): Linear (1 -> 10)
  (predict): Linear (10 -> 1)
)
"""

print(net2)     # net2 architecture
"""
Sequential (
  (0): Linear (1 -> 10)
  (1): ReLU ()
  (2): Linear (10 -> 1)
)
"""

Net(
  (hidden): Linear(in_features=1, out_features=10, bias=True)
  (predict): Linear(in_features=10, out_features=1, bias=True)
)
Sequential(
  (0): Linear(in_features=1, out_features=10, bias=True)
  (1): Sigmoid()
  (2): ReLU()
  (3): Linear(in_features=10, out_features=1, bias=True)
)


'\nSequential (\n  (0): Linear (1 -> 10)\n  (1): ReLU ()\n  (2): Linear (10 -> 1)\n)\n'

In [8]:
net1.state_dict()

OrderedDict([('hidden.weight', tensor([[ 0.7153],
                      [ 0.0510],
                      [ 0.3621],
                      [-0.6678],
                      [ 0.0536],
                      [-0.9581],
                      [-0.0574],
                      [-0.4748],
                      [ 0.3357],
                      [-0.1591]])),
             ('hidden.bias',
              tensor([ 0.8063,  0.3253, -0.6627, -0.7550, -0.8225,  0.7133,  0.1340, -0.5609,
                       0.3671,  0.6292])),
             ('predict.weight',
              tensor([[-0.2842, -0.2124,  0.1337,  0.1578,  0.0249,  0.2586,  0.1400, -0.3157,
                       -0.1820, -0.2551]])),
             ('predict.bias', tensor([0.1573]))])

In [9]:
net2.state_dict()

OrderedDict([('0.weight', tensor([[-0.3386],
                      [ 0.8098],
                      [-0.5990],
                      [ 0.0822],
                      [ 0.7084],
                      [-0.5027],
                      [-0.8980],
                      [-0.2518],
                      [-0.4367],
                      [-0.2157]])),
             ('0.bias',
              tensor([-0.9610, -0.6107, -0.7457, -0.7213,  0.2133,  0.4227, -0.2169, -0.3068,
                      -0.2993, -0.9576])),
             ('3.weight',
              tensor([[ 0.0540,  0.1327, -0.2190,  0.1100, -0.1897, -0.0151,  0.0789,  0.0441,
                        0.0907, -0.0995]])),
             ('3.bias', tensor([0.2436]))])

0.weight
0.bias
3.weight
3.bias


In [17]:
parameters = net1.state_dict()
for k,v in parameters.items():
    print(k)

hidden.weight
hidden.bias
predict.weight
predict.bias


In [18]:
parameters = net2.state_dict()
for k,v in parameters.items():
    print(k)

0.weight
0.bias
3.weight
3.bias
