In [85]:
import torch
from torch import nn, optim
import torch.nn.functional as F
from torch.autograd import Variable
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision import datasets
import time
# 定义超参数
batch_size = 32
learning_rate = 1e-3
num_epoches = 20

# 下载训练集 MNIST 手写数字训练集
train_dataset = datasets.MNIST(
    root='./data', train=True, transform=transforms.ToTensor(), download=True)

test_dataset = datasets.MNIST(
    root='./data', train=False, transform=transforms.ToTensor())

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

"""
class Logstic_Regression1(nn.Module):
    def __init__(self, in_dim, n_class):
        super(Logstic_Regression1, self).__init__()
        self.logstic = nn.Linear(in_dim, n_class)

    def forward(self, x):
        out = self.logstic(x)
        return out    
"""
#model = Logstic_Regression1(28*28, 10)

net2 = torch.nn.Sequential(
    torch.nn.Linear(784, 10),
    # torch.nn.ReLU(),
    torch.nn.Linear(10, 10)
)

parameters_all = net2.state_dict() 
parameters_1 = torch.load('logstic_model1.pth')
parameters_3 = torch.load('logstic_model3.pth')
# model.load_state_dict(parameters)

In [86]:
parameters_1['0.weight'] = parameters_1.pop('logstic.weight')
parameters_1['0.bias'] = parameters_1.pop('logstic.bias')
parameters_1

OrderedDict([('0.weight',
              tensor([[ 0.0304,  0.0145,  0.0322,  ..., -0.0154,  0.0072, -0.0085],
                      [ 0.0060, -0.0125,  0.0065,  ...,  0.0152,  0.0146,  0.0299],
                      [-0.0164, -0.0085,  0.0124,  ..., -0.0243,  0.0318, -0.0233],
                      ...,
                      [-0.0301, -0.0075, -0.0152,  ...,  0.0106, -0.0026,  0.0052],
                      [-0.0223,  0.0323, -0.0221,  ..., -0.0040,  0.0030,  0.0323],
                      [-0.0159, -0.0190, -0.0164,  ...,  0.0157,  0.0016, -0.0050]])),
             ('0.bias',
              tensor([-0.0739,  0.1572, -0.0433, -0.0935,  0.0564,  0.2139, -0.0080,  0.1060,
                      -0.3302, -0.0264]))])

In [87]:
parameters_1['0.weight'] = parameters_1.pop('logstic.weight')
parameters_1['0.bias'] = parameters_1.pop('logstic.bias')
parameters_3['1.weight'] = parameters_3.pop('logstic.weight')
parameters_3['1.bias'] = parameters_3.pop('logstic.bias')
parameters_3

OrderedDict([('1.weight',
              tensor([[ 1.2153, -0.1210,  0.0188, -0.0128, -0.0109,  0.1356,  0.0371,  0.2003,
                       -0.0087, -0.0840],
                      [-0.4054,  1.1147, -0.2494, -0.2564, -0.1963, -0.3948, -0.1654, -0.1669,
                       -0.1895, -0.2892],
                      [-0.3155, -0.2631,  1.1549, -0.1747, -0.3102, -0.4532, -0.1536, -0.2037,
                       -0.0926, -0.2224],
                      [-0.2498, -0.1537,  0.0293,  1.1062, -0.3516, -0.1344, -0.2632, -0.0410,
                       -0.2375,  0.0487],
                      [-0.4075, -0.1133, -0.1944, -0.3503,  1.1443, -0.0404, -0.0228, -0.1564,
                       -0.2146,  0.1121],
                      [-0.1851, -0.2274, -0.3904, -0.2392, -0.2042,  0.9863, -0.1618, -0.1579,
                       -0.0295, -0.2748],
                      [-0.1500,  0.0925, -0.0252, -0.3781,  0.1047, -0.0215,  1.2224, -0.2020,
                       -0.2250, -0.2325],
               

In [88]:
print(parameters_all['0.weight'].size())
print(parameters_all['0.bias'].size())
print(parameters_all['1.weight'].size())
print(parameters_all['1.bias'].size())

torch.Size([10, 784])
torch.Size([10])
torch.Size([10, 10])
torch.Size([10])


In [89]:
print(parameters_1['0.weight'].size())
print(parameters_1['0.bias'].size())
print(parameters_3['1.weight'].size())
print(parameters_3['1.bias'].size())

torch.Size([10, 784])
torch.Size([10])
torch.Size([10, 10])
torch.Size([10])


In [90]:
parameters_all = parameters_1.copy()
parameters_all.update(parameters_3)

In [91]:
net2.load_state_dict(parameters_all)

In [74]:
net2.load_state_dict(parameters_all)

RuntimeError: Error(s) in loading state_dict for Sequential:
	size mismatch for 1.weight: copying a param of torch.Size([1, 10]) from checkpoint, where the shape is torch.Size([10, 10]) in current model.
	size mismatch for 1.bias: copying a param of torch.Size([1]) from checkpoint, where the shape is torch.Size([10]) in current model.

In [77]:
print(parameters_1['logstic.weight'].size())

KeyError: 'logstic.weight'

In [10]:
print(parameters_3['logstic.bias'].size())

torch.Size([10])


In [75]:
print(parameters_all['0.weight'].size())

torch.Size([10, 784])


In [76]:
print(parameters_all['1.weight'].size())

torch.Size([10, 10])


In [24]:
parameters_1

OrderedDict([('logstic.weight',
              tensor([[ 0.0304,  0.0145,  0.0322,  ..., -0.0154,  0.0072, -0.0085],
                      [ 0.0060, -0.0125,  0.0065,  ...,  0.0152,  0.0146,  0.0299],
                      [-0.0164, -0.0085,  0.0124,  ..., -0.0243,  0.0318, -0.0233],
                      ...,
                      [-0.0301, -0.0075, -0.0152,  ...,  0.0106, -0.0026,  0.0052],
                      [-0.0223,  0.0323, -0.0221,  ..., -0.0040,  0.0030,  0.0323],
                      [-0.0159, -0.0190, -0.0164,  ...,  0.0157,  0.0016, -0.0050]])),
             ('logstic.bias',
              tensor([-0.0739,  0.1572, -0.0433, -0.0935,  0.0564,  0.2139, -0.0080,  0.1060,
                      -0.3302, -0.0264]))])

In [25]:
parameters_all

OrderedDict([('0.weight',
              tensor([[-0.0066, -0.0131,  0.0076,  ...,  0.0319,  0.0002, -0.0245],
                      [-0.0267,  0.0295, -0.0020,  ...,  0.0014, -0.0201,  0.0000],
                      [ 0.0051, -0.0321, -0.0297,  ..., -0.0203,  0.0216, -0.0002],
                      ...,
                      [ 0.0173,  0.0011,  0.0236,  ...,  0.0246,  0.0232, -0.0014],
                      [-0.0253,  0.0286,  0.0056,  ..., -0.0246,  0.0093,  0.0287],
                      [ 0.0321,  0.0271, -0.0255,  ...,  0.0004,  0.0324, -0.0306]])),
             ('0.bias',
              tensor([-0.0176,  0.0054, -0.0268,  0.0326,  0.0134, -0.0285, -0.0163,  0.0122,
                       0.0146, -0.0165])),
             ('1.weight',
              tensor([[-0.1478,  0.2805,  0.2750,  0.1247, -0.1853,  0.1047,  0.1696,  0.0236,
                        0.2315, -0.2906]])),
             ('1.bias', tensor([0.1847]))])

In [109]:
a = {'a': 100} 
a['b'] = 200 
a

{'a': 100, 'b': 200}

In [106]:
a["0.a_b"] = a["a"]
a

{'a': 100, 'b': 200, '0.a_b': 100}

In [107]:
a.pop('a')

100

In [108]:
a

{'b': 200, '0.a_b': 100}

In [110]:
a['0.a_b'] = a.pop('a')
a

{'b': 200, '0.a_b': 100}

{'0.dic': 2, 'A': 1}

In [58]:
a.update(A = a.pop('a'))

In [60]:
a = {'a': 1}

In [100]:
0.dic = a.pop('a')
a.update()

SyntaxError: invalid syntax (<ipython-input-100-e414a2df63cb>, line 1)

In [101]:
0.asd = 1

SyntaxError: invalid syntax (<ipython-input-101-9be9f2a420b3>, line 1)